spring.datasource.url=jdbc:mysql://localhost:3306/food_ordering?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=167943@@Qp
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
server.port=8080
jwt.secret=ThisIsAVerySecretKeyForJwtAuthenticationInOurApplication

# Mail Configuration (Using Gmail SMTP as an Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL_USERNAME@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
